### ISSUE TITLE
Sample / tutorial

### ISSUE THREAD

**Issue by EnricoBeltramo** [smartsenselab/sensecam-control#2]
There are some sample some samples or tutorial how to use this library? I.e how to start a continous stream etc?

Thank

**Comment by igorhenriquedias94** [comment]
Hello EnricoBeltramo.
I added an example file to use the Vapix library on the Axis camera. I normally use opencv to display images when I need to view them. This is a basic example for controlling PTZ`s cameras using the keyboard. There are many possibilities for using the library, this was just a simple use.

**Comment by EnricoBeltramo** [comment]
Thank you. I will check.
